import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link
					href="https://fonts.cdnfonts.com/css/helvetica-neue-5"
					rel="stylesheet"
				></link>
			</head>
			<body className="antialiased">{children}</body>
		</html>
	);
}
