import type { Metadata } from "next";
import "./globals.css";

import { helveticaNeue } from "@/lib/fonts";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			suppressHydrationWarning
			suppressContentEditableWarning
			className={helveticaNeue.variable}
		>
			<body className="antialiased font-sans">{children}</body>
		</html>
	);
}
