import type { Metadata } from "next";
import ErrorBoundary from "@/components/ErrorBoundary";
import "./globals.css";
import PlausibleProvider from "next-plausible";
import Script from "next/script";

import { helveticaNeue } from "@/lib/fonts";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
  return (
    <html lang="en"suppressHydrationWarning
			suppressContentEditableWarning
			className={helveticaNeue.variable}>
      <head>
        {/* Clarity tracking code */}
        <Script
          id="clarity-script"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function(c,l,a,r,i,t,y){
                  c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
                  t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
                  y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
              })(window, document, "clarity", "script", "${process.env.NEXT_PUBLIC_CLARITY_ID}");
            `,
          }}
        />
      </head>
      <body
        className={`antialiased`}
      >
        <PlausibleProvider domain="magnus-lp-git-dev-chainlabs.vercel.app">
          <ErrorBoundary>{children}</ErrorBoundary>
        </PlausibleProvider>
      </body>
    </html>
  );
}
